/**
 * AI Code Explainer — Returns purpose, inputs, outputs, architecture role for a file or function.
 * Optional: use Gemini to generate explanations; cache in docs/generated/ai-explanations/.
 */

import { NextRequest, NextResponse } from 'next/server';
import { readFile } from 'fs/promises';
import path from 'path';

const ROOT = process.cwd();
const SRC = path.join(ROOT, 'src');
const CODE_INTEL = path.join(ROOT, 'docs', 'generated', 'code-intelligence');

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const filePath = searchParams.get('filePath') ?? searchParams.get('file');
  const functionName = searchParams.get('functionName') ?? searchParams.get('function');

  if (!filePath && !functionName) {
    return NextResponse.json(
      { error: 'Provide filePath or functionName' },
      { status: 400 }
    );
  }

  try {
    if (filePath) {
      const safePath = path.normalize(filePath).replace(/^(\.\.\/)+/, '');
      if (safePath.includes('..')) {
        return NextResponse.json({ error: 'Invalid path' }, { status: 400 });
      }
      const fullPath = path.join(SRC, safePath);
      const content = await readFile(fullPath, 'utf-8').catch(() => '');
      const firstComment = content.match(/\/\*\*([\s\S]*?)\*\//)?.[1]?.trim() ?? '';
      const baseName = path.basename(safePath, '.ts');
      const codeIntelPath = path.join(CODE_INTEL, `${baseName}.md`);
      let codeIntel = '';
      try {
        codeIntel = await readFile(codeIntelPath, 'utf-8');
      } catch {
        //
      }
      return NextResponse.json({
        purpose: firstComment.split('\n')[0]?.replace(/\s*\*\s?/g, '').trim() ?? 'No description.',
        filePath: safePath,
        architectureRole: codeIntel ? 'See code-intelligence doc.' : undefined,
        docPath: codeIntel ? `/amazon_audit_faq/code` : undefined,
      });
    }

    if (functionName) {
      const formulaMatch = ['acos', 'roas', 'tacos', 'cpc', 'ctr', 'cvr', 'organicSales', 'wastedSpend'].find(
        (f) => f.toLowerCase() === functionName.toLowerCase()
      );
      if (formulaMatch) {
        return NextResponse.json({
          purpose: `Metric formula: ${functionName}. See Metrics & Formulas in the help center.`,
          inputs: 'Varies by metric (e.g. adSales, adSpend).',
          outputs: 'Numeric value.',
          architectureRole: 'amazonMetricsLibrary / formulaRegistry',
          href: '/amazon_audit_faq/formulas',
        });
      }
      return NextResponse.json({
        purpose: 'Function documentation is generated by the code-intelligence engine. Run npm run generate-docs.',
        href: '/amazon_audit_faq/code',
      });
    }

    return NextResponse.json({ error: 'Missing filePath or functionName' }, { status: 400 });
  } catch (e) {
    console.error('[explain-code]', e);
    return NextResponse.json({ error: 'Request failed' }, { status: 500 });
  }
}
